
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2025.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_GPIO_ADDR_DEVICE_ID,
		XPAR_GPIO_ADDR_BASEADDR,
		XPAR_GPIO_ADDR_INTERRUPT_PRESENT,
		XPAR_GPIO_ADDR_IS_DUAL
	},
	{
		XPAR_GPIO_CTRL_DEVICE_ID,
		XPAR_GPIO_CTRL_BASEADDR,
		XPAR_GPIO_CTRL_INTERRUPT_PRESENT,
		XPAR_GPIO_CTRL_IS_DUAL
	}
};


