/*
 * yolov4_runtime.c -- Full-network runtime for YOLOv4-416 INT8 on P_17 DPU.
 *
 * Targets ZedBoard (Zynq-7020) with the P_17 wrapper (CONV / LEAKY / POOL
 * / ADD selected by REG_LAYER_TYPE).  Concat / Upsample are done on the
 * ARM by reordering DDR buffers.
 *
 * Bring-up assumptions (driven by XSCT before this program boots):
 *   - Weights and biases for every conv layer have been loaded into a
 *     contiguous DDR region starting at WEIGHTS_BASE.  Per-layer offsets
 *     come from a parallel table generated by gen_layer_configs.py.
 *   - The calibration / inference image (NHWC int8, 3*416*416 = 519 168 B)
 *     sits at INPUT_BASE.
 *   - All cache invalidation / flushing happens around DMA boundaries.
 *
 * Control flow per layer:
 *   1. Pull layer_config_t L = LAYERS[i].
 *   2. Resolve in_a / in_b pointers via the live activation map.
 *   3. Allocate output region from the pool.
 *   4. Dispatch on op_type to dpu_exec_*() or arm_*().
 *   5. Record cycle counts.
 *   6. Decrement reference counts on inputs; pool_release() once they hit 0.
 *
 * Tiling (the hard part): the wrapper BRAM is 4 KB.  Every dpu_exec_*()
 * receives a pointer to a *full* DDR tensor and is itself responsible for
 * splitting it into (h_tile x w_tile x c) sub-tiles that fit BRAM, then
 * issuing one LOAD/COMPUTE/DRAIN cycle per tile.  The runtime here only
 * sees the layer-level granularity.
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "xil_io.h"
#include "xil_cache.h"
#include "xtime_l.h"

#include "dpu_api.h"
#include "layer_configs.h"

/* ============================== DDR map ============================== */
/* 512 MB DDR on ZedBoard.  Bottom 64 MB reserved for Linux/standalone
 * code + heap + stack.  Top region split as below.                       */

#define INPUT_BASE     ((uintptr_t)0x10000000)  /* 3*416*416 = 520 KB     */
#define WEIGHTS_BASE   ((uintptr_t)0x10100000)  /* ~64 MB of int8 weights */
#define BIAS_BASE      ((uintptr_t)0x14000000)  /* ~256 KB int32 biases   */
#define ACT_POOL_BASE  ((uintptr_t)0x14100000)  /* 224 MB activation pool */
#define ACT_POOL_BYTES ((uint32_t)(224u * 1024u * 1024u))
#define RESULT_ADDR    ((uintptr_t)0x1F000000)  /* runtime status word    */
#define MAGIC_DONE     0xD09F1234u

/* Per-layer weights/bias offset tables (auto-generated alongside LAYERS). */
extern const uint32_t LAYER_WEIGHTS_OFF[NUM_FPGA_LAYERS];   /* bytes */
extern const uint32_t LAYER_BIAS_OFF   [NUM_FPGA_LAYERS];   /* bytes */

/* Activation table: for each layer index, the DDR pointer to its output.
 * NULL == not yet produced or already recycled.                          */
static uint8_t  *activation_ptr[NUM_FPGA_LAYERS];
static uint32_t  activation_size[NUM_FPGA_LAYERS];
static uint8_t   refcount[NUM_FPGA_LAYERS];   /* how many consumers left */

/* Per-layer profile, kept for the post-run dump. */
static dpu_prof_t prof_log[NUM_FPGA_LAYERS];

/* ====================== Reference-count precompute ==================== */
/* Walk the layer table once, count how many later layers reference each
 * producer through input_a_idx / input_b_idx.  After execution we
 * decrement; when the count hits zero the buffer can be freed.           */
static void build_refcount(void)
{
    memset(refcount, 0, sizeof(refcount));
    for (int i = 0; i < NUM_FPGA_LAYERS; i++) {
        int16_t a = LAYERS[i].input_a_idx;
        int16_t b = LAYERS[i].input_b_idx;
        if (a >= 0 && a < NUM_FPGA_LAYERS) refcount[a]++;
        if (b >= 0 && b < NUM_FPGA_LAYERS) refcount[b]++;
    }
    /* The last 3 layers (YOLO heads) must never be released. */
    for (int i = NUM_FPGA_LAYERS - 3; i < NUM_FPGA_LAYERS; i++) {
        refcount[i] += 1;
    }
}

/* ============================== Helpers =============================== */
static inline uint32_t output_bytes(const layer_config_t *L)
{
    return (uint32_t)L->c_out * L->h_out * L->w_out;   /* int8 NHWC */
}

static const uint8_t *resolve_input(int16_t idx, const uint8_t *external)
{
    if (idx < 0)  return external;                /* -1 == network input */
    return activation_ptr[idx];
}

/* ============================== Main loop ============================= */
int main(void)
{
    XTime t0, t1;
    volatile uint32_t *res = (volatile uint32_t *)RESULT_ADDR;

    res[0] = 0xAAAA0001u;
    Xil_DCacheFlushRange((UINTPTR)res, 64);

    xil_printf("\r\n=== YOLOv4-416 INT8 runtime on P_17 DPU ===\r\n");
    xil_printf("Layers: %d   Pool: %u MB\r\n",
               NUM_FPGA_LAYERS, ACT_POOL_BYTES >> 20);

    if (dpu_init() != DPU_OK) {
        xil_printf("FATAL: dpu_init failed\r\n");
        goto fail;
    }
    mem_pool_t *pool = pool_create(ACT_POOL_BASE, ACT_POOL_BYTES);
    if (!pool) {
        xil_printf("FATAL: pool_create failed\r\n");
        goto fail;
    }
    build_refcount();
    memset(activation_ptr,  0, sizeof(activation_ptr));
    memset(activation_size, 0, sizeof(activation_size));

    const uint8_t *external_in = (const uint8_t *)INPUT_BASE;

    XTime_GetTime(&t0);

    for (int i = 0; i < NUM_FPGA_LAYERS; i++) {
        const layer_config_t *L = &LAYERS[i];
        dpu_prof_t            *p = &prof_log[i];
        memset(p, 0, sizeof(*p));

        const uint8_t *in_a = resolve_input(L->input_a_idx, external_in);
        const uint8_t *in_b = (L->input_b_idx >= 0)
                              ? activation_ptr[L->input_b_idx] : NULL;

        uint32_t out_bytes = output_bytes(L);
        uint8_t *out = pool_alloc(pool, out_bytes, (uint16_t)i);
        if (!out) {
            xil_printf("L%03d: pool OOM (need %u, have %u)\r\n",
                       i, out_bytes, ACT_POOL_BYTES - pool_bytes_used(pool));
            goto fail;
        }

        int rc = DPU_ERR_PARAMS;
        switch (L->op_type) {
        case OP_CONV: {
            const int8_t  *w = (const int8_t  *)(WEIGHTS_BASE + LAYER_WEIGHTS_OFF[i]);
            const int32_t *b = (const int32_t *)(BIAS_BASE    + LAYER_BIAS_OFF[i]);
            rc = dpu_exec_conv(L, in_a, w, b, out, p);
            break;
        }
        case OP_LEAKY_RELU:
            rc = dpu_exec_leaky(L, in_a, out, p);
            break;
        case OP_MAXPOOL:
            rc = dpu_exec_pool(L, in_a, out, p);
            break;
        case OP_ADD:
            if (!in_b) { xil_printf("L%03d: ADD missing input_b\r\n", i); goto fail; }
            rc = dpu_exec_add(L, in_a, in_b, out, p);
            break;
        case OP_CONCAT:
            if (!in_b) { xil_printf("L%03d: CONCAT missing input_b\r\n", i); goto fail; }
            /* Channel split: A contributes c_a, B contributes c_b, c_out=c_a+c_b */
            rc = arm_concat(L,
                            in_a, LAYERS[L->input_a_idx].c_out,
                            in_b, LAYERS[L->input_b_idx].c_out,
                            out, p);
            break;
        case OP_RESIZE:
            rc = arm_upsample(L, in_a, out, p);
            break;
        default:
            xil_printf("L%03d: unknown op_type %d\r\n", i, L->op_type);
            goto fail;
        }

        if (rc != DPU_OK) {
            xil_printf("L%03d: kernel rc=%d\r\n", i, rc);
            goto fail;
        }

        activation_ptr[i]  = out;
        activation_size[i] = out_bytes;

        /* Drop refcounts on consumed inputs */
        if (L->input_a_idx >= 0 && --refcount[L->input_a_idx] == 0) {
            pool_release(pool, (uint16_t)L->input_a_idx);
            activation_ptr[L->input_a_idx] = NULL;
        }
        if (L->input_b_idx >= 0 && --refcount[L->input_b_idx] == 0) {
            pool_release(pool, (uint16_t)L->input_b_idx);
            activation_ptr[L->input_b_idx] = NULL;
        }

        if ((i & 0x0F) == 0) {
            xil_printf("  L%03d op=%d  out=%ux%ux%u  pool=%u KB\r\n",
                       i, L->op_type, L->c_out, L->h_out, L->w_out,
                       pool_bytes_used(pool) >> 10);
        }
    }

    XTime_GetTime(&t1);
    uint64_t cycles = t1 - t0;
    uint32_t ms     = (uint32_t)(cycles / (COUNTS_PER_SECOND / 1000));

    xil_printf("\r\n=== Inference complete in %u ms ===\r\n", ms);

    /* Final detection-head outputs are activation_ptr[NUM-3..NUM-1]. */
    for (int k = 0; k < 3; k++) {
        int idx = NUM_FPGA_LAYERS - 3 + k;
        xil_printf("  head %d -> 0x%08X (%u B)\r\n",
                   k, (unsigned)(uintptr_t)activation_ptr[idx],
                   activation_size[idx]);
    }

    res[0] = MAGIC_DONE;
    res[1] = ms;
    res[2] = (uint32_t)(uintptr_t)activation_ptr[NUM_FPGA_LAYERS - 3];
    res[3] = (uint32_t)(uintptr_t)activation_ptr[NUM_FPGA_LAYERS - 2];
    res[4] = (uint32_t)(uintptr_t)activation_ptr[NUM_FPGA_LAYERS - 1];
    Xil_DCacheFlushRange((UINTPTR)res, 64);

    while (1);
    return 0;

fail:
    res[0] = 0xDEADBEEFu;
    Xil_DCacheFlushRange((UINTPTR)res, 64);
    while (1);
    return 1;
}

/* ============================ STUBS BELOW ============================= */
/* These are filled in by separate compilation units (dpu_kernels.c,
 * arm_kernels.c, mem_pool.c).  Signatures match dpu_api.h exactly.       */

#ifdef DPU_RUNTIME_INLINE_STUBS
int dpu_init(void)         { return DPU_OK; }
void dpu_reset(void)       { }
int dpu_exec_conv (const layer_config_t *L, const uint8_t *a,
                   const int8_t *w, const int32_t *b,
                   uint8_t *o, dpu_prof_t *p) { (void)L;(void)a;(void)w;(void)b;(void)o;(void)p; return DPU_OK; }
int dpu_exec_leaky(const layer_config_t *L, const uint8_t *a,
                   uint8_t *o, dpu_prof_t *p) { return DPU_OK; }
int dpu_exec_pool (const layer_config_t *L, const uint8_t *a,
                   uint8_t *o, dpu_prof_t *p) { return DPU_OK; }
int dpu_exec_add  (const layer_config_t *L, const uint8_t *a,
                   const uint8_t *b, uint8_t *o, dpu_prof_t *p) { return DPU_OK; }
int arm_concat    (const layer_config_t *L,
                   const uint8_t *a, uint16_t ca,
                   const uint8_t *b, uint16_t cb,
                   uint8_t *o, dpu_prof_t *p)
{
    /* NHWC channel concat: per spatial cell copy ca bytes from A then cb from B */
    uint32_t hw = (uint32_t)L->h_out * L->w_out;
    for (uint32_t k = 0; k < hw; k++) {
        memcpy(o + k * (ca + cb),       a + k * ca, ca);
        memcpy(o + k * (ca + cb) + ca,  b + k * cb, cb);
    }
    return DPU_OK;
}
int arm_upsample  (const layer_config_t *L, const uint8_t *a,
                   uint8_t *o, dpu_prof_t *p)
{
    /* Nearest-neighbour 2x in H and W, NHWC. */
    uint16_t H = L->h_in, W = L->w_in, C = L->c_in;
    for (uint16_t y = 0; y < H; y++) {
        for (uint16_t x = 0; x < W; x++) {
            const uint8_t *src = a + (y * W + x) * C;
            for (int dy = 0; dy < 2; dy++) {
                for (int dx = 0; dx < 2; dx++) {
                    uint8_t *dst = o + ((2*y + dy) * (2*W) + (2*x + dx)) * C;
                    memcpy(dst, src, C);
                }
            }
        }
    }
    return DPU_OK;
}
#endif

/* -------------------- Tiling sketch (CONV)  ---------------------------
 *
 * dpu_exec_conv() responsibility (lives in dpu_kernels.c, not here):
 *
 *   bytes_per_row_in   = c_in  * w_in;
 *   bytes_per_row_out  = c_out * w_out;
 *   rows_per_tile = floor((DPU_TILE_INPUT_MAX - kernel*c_in) /
 *                          bytes_per_row_in);
 *   if (rows_per_tile < kernel) -> further split across c_in groups
 *                                  (ic_tile_size register).
 *   for (tile_y = 0; tile_y < h_in; tile_y += rows_per_tile) {
 *       pack_tile_to_ddr_src(...);             // input + weights + bias
 *       conv_write(REG_ADDR_INPUT, ...);
 *       conv_write(REG_PAD_TOP,    (tile_y == 0)        ? L->pad : 0);
 *       conv_write(REG_PAD_BOTTOM, (last_tile)          ? L->pad : 0);
 *       conv_write(REG_LAYER_TYPE, 0);
 *       cmd_load(); poll_idle();
 *       cmd_start(); poll_done();
 *       cfg_datamover(out + tile_y*stride*bytes_per_row_out, tile_bytes_out);
 *       cmd_drain(); poll_dm_done();
 *       prof->n_tiles++;
 *   }
 *
 * For LEAKY/POOL/ADD the same pattern applies but with DPU_TILE_STREAM_MAX
 * because there are no weights/bias eating BRAM.  ADD keeps both A and B
 * synchronised: A is preloaded into the first half of BRAM via DMA, B is
 * streamed into s_axis directly during compute (see P_17 elem_add doc).
 *
 * Worst-case CONV in YOLOv4-416 is 3x3 @ 416x416 @ 32 IC:
 *    rows_per_tile = floor((512 - 3*32)/(32*416)) = 0  -> need ic_tile_size
 *    use ic_tile_size = 4, then tile_in = 4*3*416 ≈ 5 KB still too big
 *    -> split W as well: w_tile = 32, ic_tile = 4
 *       tile_in = 4*3*32 = 384 B  OK
 * Tile counts up to 416/32 * 416 = 5408 sub-tiles for the heaviest layer,
 * which is the dominant runtime cost.  Optimising tile shape is left to
 * dpu_kernels.c.
 * ---------------------------------------------------------------------- */
