import vitis, sys, os, shutil
xsa_path = os.path.abspath(sys.argv[1])
ws_dir   = os.path.abspath(sys.argv[2])
app_src  = os.path.abspath(sys.argv[3])
if os.path.exists(os.path.join(ws_dir, "zynq_conv_platform")):
    client = vitis.create_client(workspace=ws_dir)
    d = os.path.join(ws_dir, "conv_test", "src")
    os.makedirs(d, exist_ok=True)
    shutil.copy2(app_src, d)
    client.get_component("conv_test").build()
    sys.exit(0)
client = vitis.create_client(workspace=ws_dir)
p = client.create_platform_component(name="zynq_conv_platform", hw_design=xsa_path, os="standalone", cpu="ps7_cortexa9_0")
p.build()
xpfm = os.path.join(ws_dir, "zynq_conv_platform", "export", "zynq_conv_platform", "zynq_conv_platform.xpfm")
app = client.create_app_component(name="conv_test", platform=xpfm, domain="standalone_ps7_cortexa9_0", template="empty_application")
d = os.path.join(ws_dir, "conv_test", "src")
os.makedirs(d, exist_ok=True)
shutil.copy2(app_src, d)
app.build()
print(f"ELF: {os.path.join(ws_dir, 'conv_test', 'build', 'conv_test.elf')}")
