## =============================================================================
## ZedBoard HDMI Test - Pin Constraints
## Target: xc7z020clg484-1  (ZedBoard Rev D)
## =============================================================================

## -----------------------------------------------------------------------------
## System Clock - 100 MHz oscillator
## -----------------------------------------------------------------------------
set_property PACKAGE_PIN Y9 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
create_clock -period 10.000 -name sys_clk [get_ports sys_clk]

## -----------------------------------------------------------------------------
## HDMI Output (ADV7511) - Video Data Bus  (active during DE)
## All on 3.3V bank - LVCMOS33
## Pin mapping from ZedBoard Rev D schematic / master UCF
## -----------------------------------------------------------------------------
set_property PACKAGE_PIN Y13  [get_ports {hdmi_d[0]}]
set_property PACKAGE_PIN AA13 [get_ports {hdmi_d[1]}]
set_property PACKAGE_PIN AA14 [get_ports {hdmi_d[2]}]
set_property PACKAGE_PIN Y14  [get_ports {hdmi_d[3]}]
set_property PACKAGE_PIN AB15 [get_ports {hdmi_d[4]}]
set_property PACKAGE_PIN AB16 [get_ports {hdmi_d[5]}]
set_property PACKAGE_PIN AA16 [get_ports {hdmi_d[6]}]
set_property PACKAGE_PIN AB17 [get_ports {hdmi_d[7]}]
set_property PACKAGE_PIN AA17 [get_ports {hdmi_d[8]}]
set_property PACKAGE_PIN Y15  [get_ports {hdmi_d[9]}]
set_property PACKAGE_PIN W13  [get_ports {hdmi_d[10]}]
set_property PACKAGE_PIN W15  [get_ports {hdmi_d[11]}]
set_property PACKAGE_PIN V15  [get_ports {hdmi_d[12]}]
set_property PACKAGE_PIN U17  [get_ports {hdmi_d[13]}]
set_property PACKAGE_PIN V14  [get_ports {hdmi_d[14]}]
set_property PACKAGE_PIN V13  [get_ports {hdmi_d[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_d[*]}]

## -----------------------------------------------------------------------------
## HDMI Control Signals
## -----------------------------------------------------------------------------
set_property PACKAGE_PIN W18 [get_ports hdmi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_clk]

set_property PACKAGE_PIN U16 [get_ports hdmi_de]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_de]

set_property PACKAGE_PIN W16 [get_ports hdmi_int_n]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_int_n]

set_property PACKAGE_PIN W17 [get_ports hdmi_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_vsync]

## HD-HSYNC - verified from Digilent master XDC and ADI reference
set_property PACKAGE_PIN V17 [get_ports hdmi_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_hsync]

## S/PDIF audio output
set_property PACKAGE_PIN U15 [get_ports hdmi_spdif]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_spdif]

## -----------------------------------------------------------------------------
## HDMI I2C (directly from PL to ADV7511)
## On ZedBoard, HD-SCL and HD-SDA are directly connected to PL pins.
## These are active-low open-drain (directly emulated in VHDL with 'Z'/'0').
## The board has external pull-ups on these lines.
## -----------------------------------------------------------------------------
set_property PACKAGE_PIN AA18 [get_ports hdmi_scl]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_scl]
set_property PULLUP true [get_ports hdmi_scl]

set_property PACKAGE_PIN Y16 [get_ports hdmi_sda]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_sda]
set_property PULLUP true [get_ports hdmi_sda]

## -----------------------------------------------------------------------------
## Debug LEDs
## -----------------------------------------------------------------------------
set_property PACKAGE_PIN T22 [get_ports {led[0]}]
set_property PACKAGE_PIN T21 [get_ports {led[1]}]
set_property PACKAGE_PIN U22 [get_ports {led[2]}]
set_property PACKAGE_PIN U21 [get_ports {led[3]}]
set_property PACKAGE_PIN V22 [get_ports {led[4]}]
set_property PACKAGE_PIN W22 [get_ports {led[5]}]
set_property PACKAGE_PIN U19 [get_ports {led[6]}]
set_property PACKAGE_PIN U14 [get_ports {led[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]

## -----------------------------------------------------------------------------
## Timing constraints
## -----------------------------------------------------------------------------
## The pixel clock is generated by MMCM and Vivado automatically derives it.
## We add a false path from sys_clk to pclk domain since the I2C init
## runs on sys_clk and video runs on pclk - they don't interact after init.
## (If Vivado flags cross-domain paths, add set_clock_groups here.)

## MMCM output clock is auto-derived, no need to define manually.
## If needed:
# create_generated_clock -name pclk -source [get_pins u_mmcm/CLKIN1] \
#     -master_clock sys_clk [get_pins u_mmcm/CLKOUT0]

## Mark I2C pins as slow (no timing constraints needed for 100 kHz I2C)
set_false_path -to [get_ports hdmi_scl]
set_false_path -to [get_ports hdmi_sda]
set_false_path -from [get_ports hdmi_scl]
set_false_path -from [get_ports hdmi_sda]

## Bitstream configuration
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
